# Generated by Django 3.0.5 on 2020-05-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField(max_length=256)),
                ('content', models.TextField(max_length=1024)),
                ('image', models.FileField(upload_to='upload/')),
                ('published', models.DateTimeField()),
                ('source', models.URLField(null=True)),
            ],
        ),
    ]
