# Generated by Django 3.0.5 on 2020-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200510_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='2020-05-10 22:52:08'),
        ),
    ]
